"""
Catálogo Nacional de Códigos CIIU de 4 dígitos.
Extraído de: Documents/Codigos CIIU nivel nacional.xlsx
Total de códigos: 504
"""

# Secciones del catálogo CIIU
CIIU_SECTIONS = {
    "SECCIÓN A": "AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y PESCA",
    "SECCIÓN B": "EXPLOTACIÓN DE MINAS Y CANTERAS",
    "SECCIÓN C": "INDUSTRIAS MANUFACTURERAS",
    "SECCIÓN D": "SUMINISTRO DE ELECTRICIDAD, GAS, VAPOR Y AIRE ACONDICIONADO",
    "SECCIÓN Dian": "OTRAS CLASIFICACIONES (No hace parte de la CIIU Rev. 4 A.C 2020, es una sección establecida por la Dian)",
    "SECCIÓN E": "DISTRIBUCIÓN DE AGUA; EVACUACIÓN Y TRATAMIENTO DE AGUAS RESIDUALES, GESTIÓN DE DESECHOS Y ACTIVIDADES DE SANEAMIENTO AMBIENTAL",
    "SECCIÓN F": "CONSTRUCCIÓN",
    "SECCIÓN G": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS",
    "SECCIÓN H": "TRANSPORTE Y ALMACENAMIENTO",
    "SECCIÓN I": "ALOJAMIENTO Y SERVICIOS DE COMIDA",
    "SECCIÓN J": "INFORMACIÓN Y COMUNICACIONES",
    "SECCIÓN K": "ACTIVIDADES FINANCIERAS Y DE SEGUROS",
    "SECCIÓN L": "ACTIVIDADES INMOBILIARIAS",
    "SECCIÓN M": "ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS",
    "SECCIÓN N": "ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO",
    "SECCIÓN O": "ADMINISTRACIÓN PÚBLICA Y DEFENSA; PLANES DE SEGURIDAD SOCIAL DE AFILIACIÓN OBLIGATORIA",
    "SECCIÓN P": "EDUCACIÓN",
    "SECCIÓN Q": "ACTIVIDADES DE ATENCIÓN DE LA SALUD HUMANA Y DE ASISTENCIA SOCIAL",
    "SECCIÓN R": "ACTIVIDADES ARTÍSTICAS, DE ENTRETENIMIENTO Y RECREACIÓN",
    "SECCIÓN S": "OTRAS ACTIVIDADES DE SERVICIOS",
    "SECCIÓN T": "ACTIVIDADES DE LOS HOGARES INDIVIDUALES EN CALIDAD DE EMPLEADORES; ACTIVIDADES NO DIFERENCIADAS DE LOS HOGARES INDIVIDUALES COMO PRODUCTORES DE BIENES Y SERVICIOS PARA USO PROPIO",
    "SECCIÓN U": "ACTIVIDADES DE ORGANIZACIONES Y ENTIDADES EXTRATERRITORIALES",
}

# Lista completa de códigos CIIU de 4 dígitos
CIIU_CODES = [
    {"ciiu_code": "0111", "description": "Cultivo de cereales (excepto arroz), legumbres y semillas oleaginosas", "section_code": "SECCIÓN A", "section_name": "AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y PESCA"},
    {"ciiu_code": "0112", "description": "Cultivo de arroz", "section_code": "SECCIÓN A", "section_name": "AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y PESCA"},
    {"ciiu_code": "0113", "description": "Cultivo de hortalizas, raíces y tubérculos", "section_code": "SECCIÓN A", "section_name": "AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y PESCA"},
    {"ciiu_code": "0114", "description": "Cultivo de tabaco", "section_code": "SECCIÓN A", "section_name": "AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y PESCA"},
    {"ciiu_code": "0115", "description": "Cultivo de plantas textiles", "section_code": "SECCIÓN A", "section_name": "AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y PESCA"},
    {"ciiu_code": "0119", "description": "Otros cultivos transitorios n.c.p.", "section_code": "SECCIÓN A", "section_name": "AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y PESCA"},
    {"ciiu_code": "0121", "description": "Cultivo de frutas tropicales y subtropicales", "section_code": "SECCIÓN A", "section_name": "AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y PESCA"},
    {"ciiu_code": "0122", "description": "Cultivo de plátano y banano", "section_code": "SECCIÓN A", "section_name": "AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y PESCA"},
    {"ciiu_code": "0123", "description": "Cultivo de café", "section_code": "SECCIÓN A", "section_name": "AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y PESCA"},
    {"ciiu_code": "0124", "description": "Cultivo de caña de azúcar", "section_code": "SECCIÓN A", "section_name": "AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y PESCA"},
    {"ciiu_code": "0125", "description": "Cultivo de flor de corte", "section_code": "SECCIÓN A", "section_name": "AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y PESCA"},
    {"ciiu_code": "0126", "description": "Cultivo de palma para aceite (palma africana) y otros frutos oleaginosos", "section_code": "SECCIÓN A", "section_name": "AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y PESCA"},
    {"ciiu_code": "0127", "description": "Cultivo de plantas con las que se preparan bebidas", "section_code": "SECCIÓN A", "section_name": "AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y PESCA"},
    {"ciiu_code": "0128", "description": "Cultivo de especias y de plantas aromáticas y medicinales", "section_code": "SECCIÓN A", "section_name": "AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y PESCA"},
    {"ciiu_code": "0129", "description": "Otros cultivos permanentes n.c.p.", "section_code": "SECCIÓN A", "section_name": "AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y PESCA"},
    {"ciiu_code": "0130", "description": "Propagación de plantas (actividades de los viveros, excepto viveros forestales)", "section_code": "SECCIÓN A", "section_name": "AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y PESCA"},
    {"ciiu_code": "0141", "description": "Cría de ganado bovino y bufalino", "section_code": "SECCIÓN A", "section_name": "AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y PESCA"},
    {"ciiu_code": "0142", "description": "Cría de caballos y otros equinos", "section_code": "SECCIÓN A", "section_name": "AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y PESCA"},
    {"ciiu_code": "0143", "description": "Cría de ovejas y cabras", "section_code": "SECCIÓN A", "section_name": "AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y PESCA"},
    {"ciiu_code": "0144", "description": "Cría de ganado porcino", "section_code": "SECCIÓN A", "section_name": "AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y PESCA"},
    {"ciiu_code": "0145", "description": "Cría de aves de corral", "section_code": "SECCIÓN A", "section_name": "AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y PESCA"},
    {"ciiu_code": "0149", "description": "Cría de otros animales n.c.p.", "section_code": "SECCIÓN A", "section_name": "AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y PESCA"},
    {"ciiu_code": "0150", "description": "Explotación mixta (agrícola y pecuaria)", "section_code": "SECCIÓN A", "section_name": "AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y PESCA"},
    {"ciiu_code": "0161", "description": "Actividades de apoyo a la agricultura", "section_code": "SECCIÓN A", "section_name": "AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y PESCA"},
    {"ciiu_code": "0162", "description": "Actividades de apoyo a la ganadería", "section_code": "SECCIÓN A", "section_name": "AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y PESCA"},
    {"ciiu_code": "0163", "description": "Actividades posteriores a la cosecha", "section_code": "SECCIÓN A", "section_name": "AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y PESCA"},
    {"ciiu_code": "0164", "description": "Tratamiento de semillas para propagación", "section_code": "SECCIÓN A", "section_name": "AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y PESCA"},
    {"ciiu_code": "0170", "description": "Caza ordinaria y mediante trampas y actividades de servicios conexas", "section_code": "SECCIÓN A", "section_name": "AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y PESCA"},
    {"ciiu_code": "0210", "description": "Silvicultura y otras actividades forestales", "section_code": "SECCIÓN A", "section_name": "AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y PESCA"},
    {"ciiu_code": "0220", "description": "Extracción de madera", "section_code": "SECCIÓN A", "section_name": "AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y PESCA"},
    {"ciiu_code": "0230", "description": "Recolección de productos forestales diferentes a la madera", "section_code": "SECCIÓN A", "section_name": "AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y PESCA"},
    {"ciiu_code": "0240", "description": "Servicios de apoyo a la silvicultura", "section_code": "SECCIÓN A", "section_name": "AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y PESCA"},
    {"ciiu_code": "0311", "description": "Pesca marítima", "section_code": "SECCIÓN A", "section_name": "AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y PESCA"},
    {"ciiu_code": "0312", "description": "Pesca de agua dulce", "section_code": "SECCIÓN A", "section_name": "AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y PESCA"},
    {"ciiu_code": "0321", "description": "Acuicultura marítima", "section_code": "SECCIÓN A", "section_name": "AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y PESCA"},
    {"ciiu_code": "0322", "description": "Acuicultura de agua dulce", "section_code": "SECCIÓN A", "section_name": "AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y PESCA"},
    {"ciiu_code": "0510", "description": "Extracción de hulla (carbón de piedra)", "section_code": "SECCIÓN B", "section_name": "EXPLOTACIÓN DE MINAS Y CANTERAS"},
    {"ciiu_code": "0520", "description": "Extracción de carbón lignito", "section_code": "SECCIÓN B", "section_name": "EXPLOTACIÓN DE MINAS Y CANTERAS"},
    {"ciiu_code": "0610", "description": "Extracción de petróleo crudo", "section_code": "SECCIÓN B", "section_name": "EXPLOTACIÓN DE MINAS Y CANTERAS"},
    {"ciiu_code": "0620", "description": "Extracción de gas natural", "section_code": "SECCIÓN B", "section_name": "EXPLOTACIÓN DE MINAS Y CANTERAS"},
    {"ciiu_code": "0710", "description": "Extracción de minerales de hierro", "section_code": "SECCIÓN B", "section_name": "EXPLOTACIÓN DE MINAS Y CANTERAS"},
    {"ciiu_code": "0721", "description": "Extracción de minerales de uranio y de torio", "section_code": "SECCIÓN B", "section_name": "EXPLOTACIÓN DE MINAS Y CANTERAS"},
    {"ciiu_code": "0722", "description": "Extracción de oro y otros metales preciosos", "section_code": "SECCIÓN B", "section_name": "EXPLOTACIÓN DE MINAS Y CANTERAS"},
    {"ciiu_code": "0723", "description": "Extracción de minerales de níquel", "section_code": "SECCIÓN B", "section_name": "EXPLOTACIÓN DE MINAS Y CANTERAS"},
    {"ciiu_code": "0729", "description": "Extracción de otros minerales metalíferos no ferrosos n.c.p.", "section_code": "SECCIÓN B", "section_name": "EXPLOTACIÓN DE MINAS Y CANTERAS"},
    {"ciiu_code": "0811", "description": "Extracción de piedra, arena, arcillas comunes, yeso y anhidrita", "section_code": "SECCIÓN B", "section_name": "EXPLOTACIÓN DE MINAS Y CANTERAS"},
    {"ciiu_code": "0812", "description": "Extracción de arcillas de uso industrial, caliza, caolín y bentonitas", "section_code": "SECCIÓN B", "section_name": "EXPLOTACIÓN DE MINAS Y CANTERAS"},
    {"ciiu_code": "0820", "description": "Extracción de esmeraldas, piedras preciosas y semipreciosas", "section_code": "SECCIÓN B", "section_name": "EXPLOTACIÓN DE MINAS Y CANTERAS"},
    {"ciiu_code": "0891", "description": "Extracción de minerales para la fabricación de abonos y productos químicos", "section_code": "SECCIÓN B", "section_name": "EXPLOTACIÓN DE MINAS Y CANTERAS"},
    {"ciiu_code": "0892", "description": "Extracción de halita (sal)", "section_code": "SECCIÓN B", "section_name": "EXPLOTACIÓN DE MINAS Y CANTERAS"},
    {"ciiu_code": "0899", "description": "Extracción de otros minerales no metálicos n.c.p.", "section_code": "SECCIÓN B", "section_name": "EXPLOTACIÓN DE MINAS Y CANTERAS"},
    {"ciiu_code": "0910", "description": "Actividades de apoyo para la extracción de petróleo y de gas natural", "section_code": "SECCIÓN B", "section_name": "EXPLOTACIÓN DE MINAS Y CANTERAS"},
    {"ciiu_code": "0990", "description": "Actividades de apoyo para otras actividades de explotación de minas y canteras", "section_code": "SECCIÓN B", "section_name": "EXPLOTACIÓN DE MINAS Y CANTERAS"},
    {"ciiu_code": "1011", "description": "Procesamiento y conservación de carne y productos cárnicos", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1012", "description": "Procesamiento y conservación de pescados, crustáceos y moluscos", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1020", "description": "Procesamiento y conservación de frutas, legumbres, hortalizas y tubérculos", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1030", "description": "Elaboración de aceites y grasas de origen vegetal y animal", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1040", "description": "Elaboración de productos lácteos", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1051", "description": "Elaboración de productos de molinería", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1052", "description": "Elaboración de almidones y productos derivados del almidón", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1061", "description": "Trilla de café", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1062", "description": "Descafeinado, tostión y molienda del café", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1063", "description": "Otros derivados del café", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1071", "description": "Elaboración y refinación de azúcar", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1072", "description": "Elaboración de panela", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1081", "description": "Elaboración de productos de panadería", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1082", "description": "Elaboración de cacao, chocolate y productos de confitería", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1083", "description": "Elaboración de macarrones, fideos, alcuzcuz y productos farináceos similares", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1084", "description": "Elaboración de comidas y platos preparados", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1089", "description": "Elaboración de otros productos alimenticios n.c.p.", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1090", "description": "Elaboración de alimentos preparados para animales", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1101", "description": "Destilación, rectificación y mezcla de bebidas alcohólicas", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1102", "description": "Elaboración de bebidas fermentadas no destiladas", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1103", "description": "Producción de malta, elaboración de cervezas y otras bebidas malteadas", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1104", "description": "Elaboración de bebidas no alcohólicas, producción de aguas minerales y de otras aguas embotelladas", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1200", "description": "Elaboración de productos de tabaco", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1311", "description": "Preparación e hilatura de fibras textiles", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1312", "description": "Tejeduría de productos textiles", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1313", "description": "Acabado de productos textiles", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1391", "description": "Fabricación de tejidos de punto y ganchillo", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1392", "description": "Confección de artículos con materiales textiles, excepto prendas de vestir", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1393", "description": "Fabricación de tapetes y alfombras para pisos", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1394", "description": "Fabricación de cuerdas, cordeles, cables, bramantes y redes", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1399", "description": "Fabricación de otros artículos textiles n.c.p.", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1410", "description": "Confección de prendas de vestir, excepto prendas de piel", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1420", "description": "Fabricación de artículos de piel", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1430", "description": "Fabricación de artículos de punto y ganchillo", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1511", "description": "Curtido y recurtido de cueros; recurtido y teñido de pieles", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1512", "description": "Fabricación de artículos de viaje, bolsos de mano y artículos similares elaborados en cuero, y fabricación de artículos de talabartería y guarnicionería", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1513", "description": "Fabricación de artículos de viaje, bolsos de mano y artículos similares; artículos de talabartería y guarnicionería elaborados en otros materiales", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1521", "description": "Fabricación de calzado de cuero y piel, con cualquier tipo de suela", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1522", "description": "Fabricación de otros tipos de calzado, excepto calzado de cuero y piel", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1523", "description": "Fabricación de partes del calzado", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1610", "description": "Aserrado, acepillado e impregnación de la madera", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1620", "description": "Fabricación de hojas de madera para enchapado; fabricación de tableros contrachapados, tableros laminados, tableros de partículas y otros tableros y paneles", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1630", "description": "Fabricación de partes y piezas de madera, de carpintería y ebanistería para la construcción", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1640", "description": "Fabricación de recipientes de madera", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1690", "description": "Fabricación de otros productos de madera; fabricación de artículos de corcho, cestería y espartería", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1701", "description": "Fabricación de pulpas (pastas) celulósicas; papel y cartón", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1702", "description": "Fabricación de papel y cartón ondulado (corrugado); fabricación de envases, empaques y de embalajes de papel y cartón.", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1709", "description": "Fabricación de otros artículos de papel y cartón", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1811", "description": "Actividades de impresión", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1812", "description": "Actividades de servicios relacionados con la impresión", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1820", "description": "Producción de copias a partir de grabaciones originales", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1910", "description": "Fabricación de productos de hornos de coque", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1921", "description": "Fabricación de productos de la refinación del petróleo", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "1922", "description": "Actividad de mezcla de combustibles", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2011", "description": "Fabricación de sustancias y productos químicos básicos", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2012", "description": "Fabricación de abonos y compuestos inorgánicos nitrogenados", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2013", "description": "Fabricación de plásticos en formas primarias", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2014", "description": "Fabricación de caucho sintético en formas primarias", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2021", "description": "Fabricación de plaguicidas y otros productos químicos de uso agropecuario", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2022", "description": "Fabricación de pinturas, barnices y revestimientos similares, tintas para impresión y masillas", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2023", "description": "Fabricación de jabones y detergentes, preparados para limpiar y pulir; perfumes y preparados de tocador", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2029", "description": "Fabricación de otros productos químicos n.c.p.", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2030", "description": "Fabricación de fibras sintéticas y artificiales", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2100", "description": "Fabricación de productos farmacéuticos, sustancias químicas medicinales y productos botánicos de uso farmacéutico", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2211", "description": "Fabricación de llantas y neumáticos de caucho", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2212", "description": "Reencauche de llantas usadas", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2219", "description": "Fabricación de formas básicas de caucho y otros productos de caucho n.c.p.", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2221", "description": "Fabricación de formas básicas de plástico", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2229", "description": "Fabricación de artículos de plástico n.c.p.", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2310", "description": "Fabricación de vidrio y productos de vidrio", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2391", "description": "Fabricación de productos refractarios", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2392", "description": "Fabricación de materiales de arcilla para la construcción", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2393", "description": "Fabricación de otros productos de cerámica y porcelana", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2394", "description": "Fabricación de cemento, cal y yeso", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2395", "description": "Fabricación de artículos de hormigón, cemento y yeso", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2396", "description": "Corte, tallado y acabado de la piedra", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2399", "description": "Fabricación de otros productos minerales no metálicos n.c.p.", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2410", "description": "Industrias básicas de hierro y de acero", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2421", "description": "Industrias básicas de metales preciosos", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2429", "description": "Industrias básicas de otros metales no ferrosos", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2431", "description": "Fundición de hierro y de acero", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2432", "description": "Fundición de metales no ferrosos", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2511", "description": "Fabricación de productos metálicos para uso estructural", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2512", "description": "Fabricación de tanques, depósitos y recipientes de metal, excepto los utilizados para el envase o transporte de mercancías", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2513", "description": "Fabricación de generadores de vapor, excepto calderas de agua caliente para calefacción central", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2520", "description": "Fabricación de armas y municiones", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2591", "description": "Forja, prensado, estampado y laminado de metal; pulvimetalurgia", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2592", "description": "Tratamiento y revestimiento de metales; mecanizado", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2593", "description": "Fabricación de artículos de cuchillería, herramientas de mano y artículos de ferretería", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2599", "description": "Fabricación de otros productos elaborados de metal n.c.p.", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2610", "description": "Fabricación de componentes y tableros electrónicos", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2620", "description": "Fabricación de computadoras y de equipo periférico", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2630", "description": "Fabricación de equipos de comunicación", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2640", "description": "Fabricación de aparatos electrónicos de consumo", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2651", "description": "Fabricación de equipo de medición, prueba, navegación y control", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2652", "description": "Fabricación de relojes", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2660", "description": "Fabricación de equipo de irradiación y equipo electrónico de uso médico y terapéutico", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2670", "description": "Fabricación de instrumentos ópticos y equipo fotográfico", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2680", "description": "Fabricación de medios magnéticos y ópticos para almacenamiento de datos", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2711", "description": "Fabricación de motores, generadores y transformadores eléctricos", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2712", "description": "Fabricación de aparatos de distribución y control de la energía eléctrica", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2720", "description": "Fabricación de pilas, baterías y acumuladores eléctricos", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2731", "description": "Fabricación de hilos y cables eléctricos y de fibra óptica", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2732", "description": "Fabricación de dispositivos de cableado", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2740", "description": "Fabricación de equipos eléctricos de iluminación", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2750", "description": "Fabricación de aparatos de uso doméstico", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2790", "description": "Fabricación de otros tipos de equipo eléctrico n.c.p.", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2811", "description": "Fabricación de motores, turbinas, y partes para motores de combustión interna", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2812", "description": "Fabricación de equipos de potencia hidráulica y neumática", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2813", "description": "Fabricación de otras bombas, compresores, grifos y válvulas", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2814", "description": "Fabricación de cojinetes, engranajes, trenes de engranajes y piezas de transmisión", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2815", "description": "Fabricación de hornos, hogares y quemadores industriales", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2816", "description": "Fabricación de equipo de elevación y manipulación", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2817", "description": "Fabricación de maquinaria y equipo de oficina (excepto computadoras y equipo periférico)", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2818", "description": "Fabricación de herramientas manuales con motor", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2819", "description": "Fabricación de otros tipos de maquinaria y equipo de uso general n.c.p.", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2821", "description": "Fabricación de maquinaria agropecuaria y forestal", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2822", "description": "Fabricación de máquinas formadoras de metal y de máquinas herramienta", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2823", "description": "Fabricación de maquinaria para la metalurgia", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2824", "description": "Fabricación de maquinaria para explotación de minas y canteras y para obras de construcción", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2825", "description": "Fabricación de maquinaria para la elaboración de alimentos, bebidas y tabaco", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2826", "description": "Fabricación de maquinaria para la elaboración de productos textiles, prendas de vestir y cueros", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2829", "description": "Fabricación de otros tipos de maquinaria y equipo de uso especial n.c.p.", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2910", "description": "Fabricación de vehículos automotores y sus motores", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2920", "description": "Fabricación de carrocerías para vehículos automotores; fabricación de remolques y semirremolques", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "2930", "description": "Fabricación de partes, piezas (autopartes) y accesorios (lujos) para vehículos automotores", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "3011", "description": "Construcción de barcos y de estructuras flotantes", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "3012", "description": "Construcción de embarcaciones de recreo y deporte", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "3020", "description": "Fabricación de locomotoras y de material rodante para ferrocarriles", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "3030", "description": "Fabricación de aeronaves, naves espaciales y de maquinaria conexa", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "3040", "description": "Fabricación de vehículos militares de combate", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "3091", "description": "Fabricación de motocicletas", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "3092", "description": "Fabricación de bicicletas y de sillas de ruedas para personas con discapacidad", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "3099", "description": "Fabricación de otros tipos de equipo de transporte n.c.p.", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "3110", "description": "Fabricación de muebles", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "3120", "description": "Fabricación de colchones y somieres", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "3210", "description": "Fabricación de joyas, bisutería y artículos conexos", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "3220", "description": "Fabricación de instrumentos musicales", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "3230", "description": "Fabricación de artículos y equipo para la práctica del deporte", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "3240", "description": "Fabricación de juegos, juguetes y rompecabezas", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "3250", "description": "Fabricación de instrumentos, aparatos y materiales médicos y odontológicos (incluido mobiliario)", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "3290", "description": "Otras industrias manufactureras n.c.p.", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "3311", "description": "Mantenimiento y reparación especializado de productos elaborados en metal", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "3312", "description": "Mantenimiento y reparación especializado de maquinaria y equipo", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "3313", "description": "Mantenimiento y reparación especializado de equipo electrónico y óptico", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "3314", "description": "Mantenimiento y reparación especializado de equipo eléctrico", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "3315", "description": "Mantenimiento y reparación especializado de equipo de transporte, excepto los vehículos automotores, motocicletas y bicicletas", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "3319", "description": "Mantenimiento y reparación de otros tipos de equipos y sus componentes n.c.p.", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "3320", "description": "Instalación especializada de maquinaria y equipo industrial", "section_code": "SECCIÓN C", "section_name": "INDUSTRIAS MANUFACTURERAS"},
    {"ciiu_code": "3511", "description": "Generación de energía eléctrica", "section_code": "SECCIÓN D", "section_name": "SUMINISTRO DE ELECTRICIDAD, GAS, VAPOR Y AIRE ACONDICIONADO"},
    {"ciiu_code": "3512", "description": "Transmisión de energía eléctrica", "section_code": "SECCIÓN D", "section_name": "SUMINISTRO DE ELECTRICIDAD, GAS, VAPOR Y AIRE ACONDICIONADO"},
    {"ciiu_code": "3513", "description": "Distribución de energía eléctrica", "section_code": "SECCIÓN D", "section_name": "SUMINISTRO DE ELECTRICIDAD, GAS, VAPOR Y AIRE ACONDICIONADO"},
    {"ciiu_code": "3514", "description": "Comercialización de energía eléctrica", "section_code": "SECCIÓN D", "section_name": "SUMINISTRO DE ELECTRICIDAD, GAS, VAPOR Y AIRE ACONDICIONADO"},
    {"ciiu_code": "3520", "description": "Producción de gas; distribución de combustibles gaseosos por tuberías", "section_code": "SECCIÓN D", "section_name": "SUMINISTRO DE ELECTRICIDAD, GAS, VAPOR Y AIRE ACONDICIONADO"},
    {"ciiu_code": "3530", "description": "Suministro de vapor y aire acondicionado", "section_code": "SECCIÓN D", "section_name": "SUMINISTRO DE ELECTRICIDAD, GAS, VAPOR Y AIRE ACONDICIONADO"},
    {"ciiu_code": "3600", "description": "Captación, tratamiento y distribución de agua", "section_code": "SECCIÓN E", "section_name": "DISTRIBUCIÓN DE AGUA; EVACUACIÓN Y TRATAMIENTO DE AGUAS RESIDUALES, GESTIÓN DE DESECHOS Y ACTIVIDADES DE SANEAMIENTO AMBIENTAL"},
    {"ciiu_code": "3700", "description": "Evacuación y tratamiento de aguas residuales", "section_code": "SECCIÓN E", "section_name": "DISTRIBUCIÓN DE AGUA; EVACUACIÓN Y TRATAMIENTO DE AGUAS RESIDUALES, GESTIÓN DE DESECHOS Y ACTIVIDADES DE SANEAMIENTO AMBIENTAL"},
    {"ciiu_code": "3811", "description": "Recolección de desechos no peligrosos", "section_code": "SECCIÓN E", "section_name": "DISTRIBUCIÓN DE AGUA; EVACUACIÓN Y TRATAMIENTO DE AGUAS RESIDUALES, GESTIÓN DE DESECHOS Y ACTIVIDADES DE SANEAMIENTO AMBIENTAL"},
    {"ciiu_code": "3812", "description": "Recolección de desechos peligrosos", "section_code": "SECCIÓN E", "section_name": "DISTRIBUCIÓN DE AGUA; EVACUACIÓN Y TRATAMIENTO DE AGUAS RESIDUALES, GESTIÓN DE DESECHOS Y ACTIVIDADES DE SANEAMIENTO AMBIENTAL"},
    {"ciiu_code": "3821", "description": "Tratamiento y disposición de desechos no peligrosos", "section_code": "SECCIÓN E", "section_name": "DISTRIBUCIÓN DE AGUA; EVACUACIÓN Y TRATAMIENTO DE AGUAS RESIDUALES, GESTIÓN DE DESECHOS Y ACTIVIDADES DE SANEAMIENTO AMBIENTAL"},
    {"ciiu_code": "3822", "description": "Tratamiento y disposición de desechos peligrosos", "section_code": "SECCIÓN E", "section_name": "DISTRIBUCIÓN DE AGUA; EVACUACIÓN Y TRATAMIENTO DE AGUAS RESIDUALES, GESTIÓN DE DESECHOS Y ACTIVIDADES DE SANEAMIENTO AMBIENTAL"},
    {"ciiu_code": "3830", "description": "Recuperación de materiales", "section_code": "SECCIÓN E", "section_name": "DISTRIBUCIÓN DE AGUA; EVACUACIÓN Y TRATAMIENTO DE AGUAS RESIDUALES, GESTIÓN DE DESECHOS Y ACTIVIDADES DE SANEAMIENTO AMBIENTAL"},
    {"ciiu_code": "3900", "description": "Actividades de saneamiento ambiental y otros servicios de gestión de desechos", "section_code": "SECCIÓN E", "section_name": "DISTRIBUCIÓN DE AGUA; EVACUACIÓN Y TRATAMIENTO DE AGUAS RESIDUALES, GESTIÓN DE DESECHOS Y ACTIVIDADES DE SANEAMIENTO AMBIENTAL"},
    {"ciiu_code": "4111", "description": "Construcción de edificios residenciales", "section_code": "SECCIÓN F", "section_name": "CONSTRUCCIÓN"},
    {"ciiu_code": "4112", "description": "Construcción de edificios no residenciales", "section_code": "SECCIÓN F", "section_name": "CONSTRUCCIÓN"},
    {"ciiu_code": "4210", "description": "Construcción de carreteras y vías de ferrocarril", "section_code": "SECCIÓN F", "section_name": "CONSTRUCCIÓN"},
    {"ciiu_code": "4220", "description": "Construcción de proyectos de servicio público", "section_code": "SECCIÓN F", "section_name": "CONSTRUCCIÓN"},
    {"ciiu_code": "4290", "description": "Construcción de otras obras de ingeniería civil", "section_code": "SECCIÓN F", "section_name": "CONSTRUCCIÓN"},
    {"ciiu_code": "4311", "description": "Demolición", "section_code": "SECCIÓN F", "section_name": "CONSTRUCCIÓN"},
    {"ciiu_code": "4312", "description": "Preparación del terreno", "section_code": "SECCIÓN F", "section_name": "CONSTRUCCIÓN"},
    {"ciiu_code": "4321", "description": "Instalaciones eléctricas", "section_code": "SECCIÓN F", "section_name": "CONSTRUCCIÓN"},
    {"ciiu_code": "4322", "description": "Instalaciones de fontanería, calefacción y aire acondicionado", "section_code": "SECCIÓN F", "section_name": "CONSTRUCCIÓN"},
    {"ciiu_code": "4329", "description": "Otras instalaciones especializadas", "section_code": "SECCIÓN F", "section_name": "CONSTRUCCIÓN"},
    {"ciiu_code": "4330", "description": "Terminación y acabado de edificios y obras de ingeniería civil", "section_code": "SECCIÓN F", "section_name": "CONSTRUCCIÓN"},
    {"ciiu_code": "4390", "description": "Otras actividades especializadas para la construcción de edificios y obras de ingeniería civil", "section_code": "SECCIÓN F", "section_name": "CONSTRUCCIÓN"},
    {"ciiu_code": "4511", "description": "Comercio de vehículos automotores nuevos", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4512", "description": "Comercio de vehículos automotores usados", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4520", "description": "Mantenimiento y reparación de vehículos automotores", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4530", "description": "Comercio de partes, piezas (autopartes) y accesorios (lujos) para vehículos automotores", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4541", "description": "Comercio de motocicletas y de sus partes, piezas y accesorios", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4542", "description": "Mantenimiento y reparación de motocicletas y de sus partes y piezas", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4610", "description": "Comercio al por mayor a cambio de una retribución o por contrata", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4620", "description": "Comercio al por mayor de materias primas agropecuarias; animales vivos", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4631", "description": "Comercio al por mayor de productos alimenticios", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4632", "description": "Comercio al por mayor de bebidas y tabaco", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4641", "description": "Comercio al por mayor de productos textiles, productos confeccionados para uso doméstico", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4642", "description": "Comercio al por mayor de prendas de vestir", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4643", "description": "Comercio al por mayor de calzado", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4644", "description": "Comercio al por mayor de aparatos y equipo de uso doméstico", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4645", "description": "Comercio al por mayor de productos farmacéuticos, medicinales, cosméticos y de tocador", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4649", "description": "Comercio al por mayor de otros utensilios domésticos n.c.p.", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4651", "description": "Comercio al por mayor de computadores, equipo periférico y programas de informática", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4652", "description": "Comercio al por mayor de equipo, partes y piezas electrónicos y de telecomunicaciones", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4653", "description": "Comercio al por mayor de maquinaria y equipo agropecuarios", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4659", "description": "Comercio al por mayor de otros tipos de maquinaria y equipo n.c.p.", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4661", "description": "Comercio al por mayor de combustibles sólidos, líquidos, gaseosos y productos conexos", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4662", "description": "Comercio al por mayor de metales y productos metalíferos", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4663", "description": "Comercio al por mayor de materiales de construcción, artículos de ferretería, pinturas, productos de vidrio, equipo y materiales de fontanería y calefacción", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4664", "description": "Comercio al por mayor de productos químicos básicos, cauchos y plásticos en formas primarias y productos químicos de uso agropecuario", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4665", "description": "Comercio al por mayor de desperdicios, desechos y chatarra", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4669", "description": "Comercio al por mayor de otros productos n.c.p.", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4690", "description": "Comercio al por mayor no especializado", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4711", "description": "Comercio al por menor en establecimientos no especializados con surtido compuesto principalmente por alimentos, bebidas o tabaco", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4719", "description": "Comercio al por menor en establecimientos no especializados, con surtido compuesto principalmente por productos diferentes de alimentos (víveres en general), bebidas y tabaco", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4721", "description": "Comercio al por menor de productos agrícolas para el consumo en establecimientos especializados", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4722", "description": "Comercio al por menor de leche, productos lácteos y huevos, en establecimientos especializados", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4723", "description": "Comercio al por menor de carnes (incluye aves de corral), productos cárnicos, pescados y productos de mar, en establecimientos especializados", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4724", "description": "Comercio al por menor de bebidas y productos del tabaco, en establecimientos especializados", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4729", "description": "Comercio al por menor de otros productos alimenticios n.c.p., en establecimientos especializados", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4731", "description": "Comercio al por menor de combustible para automotores", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4732", "description": "Comercio al por menor de lubricantes (aceites, grasas), aditivos y productos de limpieza para vehículos automotores", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4741", "description": "Comercio al por menor de computadores, equipos periféricos, programas de informática y equipos de telecomunicaciones en establecimientos especializados", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4742", "description": "Comercio al por menor de equipos y aparatos de sonido y de video, en establecimientos especializados", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4751", "description": "Comercio al por menor de productos textiles en establecimientos especializados", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4752", "description": "Comercio al por menor de artículos de ferretería, pinturas y productos de vidrio en establecimientos especializados", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4753", "description": "Comercio al por menor de tapices, alfombras y cubrimientos para paredes y pisos en establecimientos especializados", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4754", "description": "Comercio al por menor de electrodomésticos y gasodomésticos de uso doméstico, muebles y equipos de iluminación", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4755", "description": "Comercio al por menor de artículos y utensilios de uso doméstico", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4759", "description": "Comercio al por menor de otros artículos domésticos en establecimientos especializados", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4761", "description": "Comercio al por menor de libros, periódicos, materiales y artículos de papelería y escritorio, en establecimientos especializados", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4762", "description": "Comercio al por menor de artículos deportivos, en establecimientos especializados", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4769", "description": "Comercio al por menor de otros artículos culturales y de entretenimiento n.c.p. en establecimientos especializados", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4771", "description": "Comercio al por menor de prendas de vestir y sus accesorios (incluye artículos de piel) en establecimientos especializados", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4772", "description": "Comercio al por menor de todo tipo de calzado y artículos de cuero y sucedáneos del cuero en establecimientos especializados.", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4773", "description": "Comercio al por menor de productos farmacéuticos y medicinales, cosméticos y artículos de tocador en establecimientos especializados", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4774", "description": "Comercio al por menor de otros productos nuevos en establecimientos especializados", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4775", "description": "Comercio al por menor de artículos de segunda mano", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4781", "description": "Comercio al por menor de alimentos, bebidas y tabaco, en puestos de venta móviles", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4782", "description": "Comercio al por menor de productos textiles, prendas de vestir y calzado, en puestos de venta móviles", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4789", "description": "Comercio al por menor de otros productos en puestos de venta móviles", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4791", "description": "Comercio al por menor realizado a través de Internet", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4792", "description": "Comercio al por menor realizado a través de casas de venta o por correo", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4799", "description": "Otros tipos de comercio al por menor no realizado en establecimientos, puestos de venta o mercados.", "section_code": "SECCIÓN G", "section_name": "COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS"},
    {"ciiu_code": "4911", "description": "Transporte férreo de pasajeros", "section_code": "SECCIÓN H", "section_name": "TRANSPORTE Y ALMACENAMIENTO"},
    {"ciiu_code": "4912", "description": "Transporte férreo de carga", "section_code": "SECCIÓN H", "section_name": "TRANSPORTE Y ALMACENAMIENTO"},
    {"ciiu_code": "4921", "description": "Transporte de pasajeros", "section_code": "SECCIÓN H", "section_name": "TRANSPORTE Y ALMACENAMIENTO"},
    {"ciiu_code": "4922", "description": "Transporte mixto", "section_code": "SECCIÓN H", "section_name": "TRANSPORTE Y ALMACENAMIENTO"},
    {"ciiu_code": "4923", "description": "Transporte de carga por carretera", "section_code": "SECCIÓN H", "section_name": "TRANSPORTE Y ALMACENAMIENTO"},
    {"ciiu_code": "4930", "description": "Transporte por tuberías", "section_code": "SECCIÓN H", "section_name": "TRANSPORTE Y ALMACENAMIENTO"},
    {"ciiu_code": "5011", "description": "Transporte de pasajeros marítimo y de cabotaje", "section_code": "SECCIÓN H", "section_name": "TRANSPORTE Y ALMACENAMIENTO"},
    {"ciiu_code": "5012", "description": "Transporte de carga marítimo y de cabotaje", "section_code": "SECCIÓN H", "section_name": "TRANSPORTE Y ALMACENAMIENTO"},
    {"ciiu_code": "5021", "description": "Transporte fluvial de pasajeros", "section_code": "SECCIÓN H", "section_name": "TRANSPORTE Y ALMACENAMIENTO"},
    {"ciiu_code": "5022", "description": "Transporte fluvial de carga", "section_code": "SECCIÓN H", "section_name": "TRANSPORTE Y ALMACENAMIENTO"},
    {"ciiu_code": "5111", "description": "Transporte aéreo nacional de pasajeros", "section_code": "SECCIÓN H", "section_name": "TRANSPORTE Y ALMACENAMIENTO"},
    {"ciiu_code": "5112", "description": "Transporte aéreo internacional de pasajeros", "section_code": "SECCIÓN H", "section_name": "TRANSPORTE Y ALMACENAMIENTO"},
    {"ciiu_code": "5121", "description": "Transporte aéreo nacional de carga", "section_code": "SECCIÓN H", "section_name": "TRANSPORTE Y ALMACENAMIENTO"},
    {"ciiu_code": "5122", "description": "Transporte aéreo internacional de carga", "section_code": "SECCIÓN H", "section_name": "TRANSPORTE Y ALMACENAMIENTO"},
    {"ciiu_code": "5210", "description": "Almacenamiento y depósito", "section_code": "SECCIÓN H", "section_name": "TRANSPORTE Y ALMACENAMIENTO"},
    {"ciiu_code": "5221", "description": "Actividades de estaciones, vías y servicios complementarios para el transporte terrestre", "section_code": "SECCIÓN H", "section_name": "TRANSPORTE Y ALMACENAMIENTO"},
    {"ciiu_code": "5222", "description": "Actividades de puertos y servicios complementarios para el transporte acuático", "section_code": "SECCIÓN H", "section_name": "TRANSPORTE Y ALMACENAMIENTO"},
    {"ciiu_code": "5223", "description": "Actividades de aeropuertos, servicios de navegación aérea y demás actividades conexas al transporte aéreo", "section_code": "SECCIÓN H", "section_name": "TRANSPORTE Y ALMACENAMIENTO"},
    {"ciiu_code": "5224", "description": "Manipulación de carga", "section_code": "SECCIÓN H", "section_name": "TRANSPORTE Y ALMACENAMIENTO"},
    {"ciiu_code": "5229", "description": "Otras actividades complementarias al transporte", "section_code": "SECCIÓN H", "section_name": "TRANSPORTE Y ALMACENAMIENTO"},
    {"ciiu_code": "5310", "description": "Actividades postales nacionales", "section_code": "SECCIÓN H", "section_name": "TRANSPORTE Y ALMACENAMIENTO"},
    {"ciiu_code": "5320", "description": "Actividades de mensajería", "section_code": "SECCIÓN H", "section_name": "TRANSPORTE Y ALMACENAMIENTO"},
    {"ciiu_code": "5511", "description": "Alojamiento en hoteles", "section_code": "SECCIÓN I", "section_name": "ALOJAMIENTO Y SERVICIOS DE COMIDA"},
    {"ciiu_code": "5512", "description": "Alojamiento en apartahoteles", "section_code": "SECCIÓN I", "section_name": "ALOJAMIENTO Y SERVICIOS DE COMIDA"},
    {"ciiu_code": "5513", "description": "Alojamiento en centros vacacionales", "section_code": "SECCIÓN I", "section_name": "ALOJAMIENTO Y SERVICIOS DE COMIDA"},
    {"ciiu_code": "5514", "description": "Alojamiento rural", "section_code": "SECCIÓN I", "section_name": "ALOJAMIENTO Y SERVICIOS DE COMIDA"},
    {"ciiu_code": "5519", "description": "Otros tipos de alojamientos para visitantes", "section_code": "SECCIÓN I", "section_name": "ALOJAMIENTO Y SERVICIOS DE COMIDA"},
    {"ciiu_code": "5520", "description": "Actividades de zonas de camping y parques para vehículos recreacionales", "section_code": "SECCIÓN I", "section_name": "ALOJAMIENTO Y SERVICIOS DE COMIDA"},
    {"ciiu_code": "5530", "description": "Servicio por horas", "section_code": "SECCIÓN I", "section_name": "ALOJAMIENTO Y SERVICIOS DE COMIDA"},
    {"ciiu_code": "5590", "description": "Otros tipos de alojamiento n.c.p.", "section_code": "SECCIÓN I", "section_name": "ALOJAMIENTO Y SERVICIOS DE COMIDA"},
    {"ciiu_code": "5611", "description": "Expendio a la mesa de comidas preparadas", "section_code": "SECCIÓN I", "section_name": "ALOJAMIENTO Y SERVICIOS DE COMIDA"},
    {"ciiu_code": "5612", "description": "Expendio por autoservicio de comidas preparadas", "section_code": "SECCIÓN I", "section_name": "ALOJAMIENTO Y SERVICIOS DE COMIDA"},
    {"ciiu_code": "5613", "description": "Expendio de comidas preparadas en cafeterías", "section_code": "SECCIÓN I", "section_name": "ALOJAMIENTO Y SERVICIOS DE COMIDA"},
    {"ciiu_code": "5619", "description": "Otros tipos de expendio de comidas preparadas n.c.p.", "section_code": "SECCIÓN I", "section_name": "ALOJAMIENTO Y SERVICIOS DE COMIDA"},
    {"ciiu_code": "5621", "description": "Catering para eventos", "section_code": "SECCIÓN I", "section_name": "ALOJAMIENTO Y SERVICIOS DE COMIDA"},
    {"ciiu_code": "5629", "description": "Actividades de otros servicios de comidas", "section_code": "SECCIÓN I", "section_name": "ALOJAMIENTO Y SERVICIOS DE COMIDA"},
    {"ciiu_code": "5630", "description": "Expendio de bebidas alcohólicas para el consumo dentro del establecimiento", "section_code": "SECCIÓN I", "section_name": "ALOJAMIENTO Y SERVICIOS DE COMIDA"},
    {"ciiu_code": "5811", "description": "Edición de libros", "section_code": "SECCIÓN J", "section_name": "INFORMACIÓN Y COMUNICACIONES"},
    {"ciiu_code": "5812", "description": "Edición de directorios y listas de correo", "section_code": "SECCIÓN J", "section_name": "INFORMACIÓN Y COMUNICACIONES"},
    {"ciiu_code": "5813", "description": "Edición de periódicos, revistas y otras publicaciones periódicas", "section_code": "SECCIÓN J", "section_name": "INFORMACIÓN Y COMUNICACIONES"},
    {"ciiu_code": "5819", "description": "Otros trabajos de edición", "section_code": "SECCIÓN J", "section_name": "INFORMACIÓN Y COMUNICACIONES"},
    {"ciiu_code": "5820", "description": "Edición de programas de informática (software)", "section_code": "SECCIÓN J", "section_name": "INFORMACIÓN Y COMUNICACIONES"},
    {"ciiu_code": "5911", "description": "Actividades de producción de películas cinematográficas, videos, programas, anuncios y comerciales de televisión", "section_code": "SECCIÓN J", "section_name": "INFORMACIÓN Y COMUNICACIONES"},
    {"ciiu_code": "5912", "description": "Actividades de posproducción de películas cinematográficas, videos, programas, anuncios y comerciales de televisión", "section_code": "SECCIÓN J", "section_name": "INFORMACIÓN Y COMUNICACIONES"},
    {"ciiu_code": "5913", "description": "Actividades de distribución de películas cinematográficas, videos, programas, anuncios y comerciales de televisión", "section_code": "SECCIÓN J", "section_name": "INFORMACIÓN Y COMUNICACIONES"},
    {"ciiu_code": "5914", "description": "Actividades de exhibición de películas cinematográficas y videos", "section_code": "SECCIÓN J", "section_name": "INFORMACIÓN Y COMUNICACIONES"},
    {"ciiu_code": "5920", "description": "Actividades de grabación de sonido y edición de música", "section_code": "SECCIÓN J", "section_name": "INFORMACIÓN Y COMUNICACIONES"},
    {"ciiu_code": "6010", "description": "Actividades de programación y transmisión en el servicio de radiodifusión sonora", "section_code": "SECCIÓN J", "section_name": "INFORMACIÓN Y COMUNICACIONES"},
    {"ciiu_code": "6020", "description": "Actividades de programación y transmisión de televisión", "section_code": "SECCIÓN J", "section_name": "INFORMACIÓN Y COMUNICACIONES"},
    {"ciiu_code": "6110", "description": "Actividades de telecomunicaciones alámbricas", "section_code": "SECCIÓN J", "section_name": "INFORMACIÓN Y COMUNICACIONES"},
    {"ciiu_code": "6120", "description": "Actividades de telecomunicaciones inalámbricas", "section_code": "SECCIÓN J", "section_name": "INFORMACIÓN Y COMUNICACIONES"},
    {"ciiu_code": "6130", "description": "Actividades de telecomunicación satelital", "section_code": "SECCIÓN J", "section_name": "INFORMACIÓN Y COMUNICACIONES"},
    {"ciiu_code": "6190", "description": "Otras actividades de telecomunicaciones", "section_code": "SECCIÓN J", "section_name": "INFORMACIÓN Y COMUNICACIONES"},
    {"ciiu_code": "6201", "description": "Actividades de desarrollo de sistemas informáticos (planificación, análisis, diseño, programación, pruebas)", "section_code": "SECCIÓN J", "section_name": "INFORMACIÓN Y COMUNICACIONES"},
    {"ciiu_code": "6202", "description": "Actividades de consultoría informática y actividades de administración de instalaciones informáticas", "section_code": "SECCIÓN J", "section_name": "INFORMACIÓN Y COMUNICACIONES"},
    {"ciiu_code": "6209", "description": "Otras actividades de tecnologías de información y actividades de servicios informáticos", "section_code": "SECCIÓN J", "section_name": "INFORMACIÓN Y COMUNICACIONES"},
    {"ciiu_code": "6311", "description": "Procesamiento de datos, alojamiento (hosting) y actividades relacionadas", "section_code": "SECCIÓN J", "section_name": "INFORMACIÓN Y COMUNICACIONES"},
    {"ciiu_code": "6312", "description": "Portales web", "section_code": "SECCIÓN J", "section_name": "INFORMACIÓN Y COMUNICACIONES"},
    {"ciiu_code": "6391", "description": "Actividades de agencias de noticias", "section_code": "SECCIÓN J", "section_name": "INFORMACIÓN Y COMUNICACIONES"},
    {"ciiu_code": "6399", "description": "Otras actividades de servicio de información n.c.p.", "section_code": "SECCIÓN J", "section_name": "INFORMACIÓN Y COMUNICACIONES"},
    {"ciiu_code": "6411", "description": "Banco Central", "section_code": "SECCIÓN K", "section_name": "ACTIVIDADES FINANCIERAS Y DE SEGUROS"},
    {"ciiu_code": "6412", "description": "Bancos comerciales", "section_code": "SECCIÓN K", "section_name": "ACTIVIDADES FINANCIERAS Y DE SEGUROS"},
    {"ciiu_code": "6421", "description": "Actividades de las corporaciones financieras", "section_code": "SECCIÓN K", "section_name": "ACTIVIDADES FINANCIERAS Y DE SEGUROS"},
    {"ciiu_code": "6422", "description": "Actividades de las compañías de financiamiento", "section_code": "SECCIÓN K", "section_name": "ACTIVIDADES FINANCIERAS Y DE SEGUROS"},
    {"ciiu_code": "6423", "description": "Banca de segundo piso", "section_code": "SECCIÓN K", "section_name": "ACTIVIDADES FINANCIERAS Y DE SEGUROS"},
    {"ciiu_code": "6424", "description": "Actividades de las cooperativas financieras", "section_code": "SECCIÓN K", "section_name": "ACTIVIDADES FINANCIERAS Y DE SEGUROS"},
    {"ciiu_code": "6431", "description": "Fideicomisos, fondos y entidades financieras similares", "section_code": "SECCIÓN K", "section_name": "ACTIVIDADES FINANCIERAS Y DE SEGUROS"},
    {"ciiu_code": "6432", "description": "Fondos de cesantías", "section_code": "SECCIÓN K", "section_name": "ACTIVIDADES FINANCIERAS Y DE SEGUROS"},
    {"ciiu_code": "6491", "description": "Leasing financiero (arrendamiento financiero)", "section_code": "SECCIÓN K", "section_name": "ACTIVIDADES FINANCIERAS Y DE SEGUROS"},
    {"ciiu_code": "6492", "description": "Actividades financieras de fondos de empleados y otras formas asociativas del sector solidario", "section_code": "SECCIÓN K", "section_name": "ACTIVIDADES FINANCIERAS Y DE SEGUROS"},
    {"ciiu_code": "6493", "description": "Actividades de compra de cartera o factoring", "section_code": "SECCIÓN K", "section_name": "ACTIVIDADES FINANCIERAS Y DE SEGUROS"},
    {"ciiu_code": "6494", "description": "Otras actividades de distribución de fondos", "section_code": "SECCIÓN K", "section_name": "ACTIVIDADES FINANCIERAS Y DE SEGUROS"},
    {"ciiu_code": "6495", "description": "Instituciones especiales oficiales", "section_code": "SECCIÓN K", "section_name": "ACTIVIDADES FINANCIERAS Y DE SEGUROS"},
    {"ciiu_code": "6496", "description": "Capitalización", "section_code": "SECCIÓN K", "section_name": "ACTIVIDADES FINANCIERAS Y DE SEGUROS"},
    {"ciiu_code": "6499", "description": "Otras actividades de servicio financiero, excepto las de seguros y pensiones n.c.p.", "section_code": "SECCIÓN K", "section_name": "ACTIVIDADES FINANCIERAS Y DE SEGUROS"},
    {"ciiu_code": "6511", "description": "Seguros generales", "section_code": "SECCIÓN K", "section_name": "ACTIVIDADES FINANCIERAS Y DE SEGUROS"},
    {"ciiu_code": "6512", "description": "Seguros de vida", "section_code": "SECCIÓN K", "section_name": "ACTIVIDADES FINANCIERAS Y DE SEGUROS"},
    {"ciiu_code": "6513", "description": "Reaseguros", "section_code": "SECCIÓN K", "section_name": "ACTIVIDADES FINANCIERAS Y DE SEGUROS"},
    {"ciiu_code": "6515", "description": "Seguros de salud", "section_code": "SECCIÓN K", "section_name": "ACTIVIDADES FINANCIERAS Y DE SEGUROS"},
    {"ciiu_code": "6521", "description": "Servicios de seguros sociales de salud", "section_code": "SECCIÓN K", "section_name": "ACTIVIDADES FINANCIERAS Y DE SEGUROS"},
    {"ciiu_code": "6522", "description": "Servicios de seguros sociales de riesgos laborales", "section_code": "SECCIÓN K", "section_name": "ACTIVIDADES FINANCIERAS Y DE SEGUROS"},
    {"ciiu_code": "6523", "description": "Servicios de seguros sociales en riesgos de familia", "section_code": "SECCIÓN K", "section_name": "ACTIVIDADES FINANCIERAS Y DE SEGUROS"},
    {"ciiu_code": "6531", "description": "Régimen de prima media con prestación definida (RPM)", "section_code": "SECCIÓN K", "section_name": "ACTIVIDADES FINANCIERAS Y DE SEGUROS"},
    {"ciiu_code": "6532", "description": "Régimen de ahorro con solidaridad (RAIS).", "section_code": "SECCIÓN K", "section_name": "ACTIVIDADES FINANCIERAS Y DE SEGUROS"},
    {"ciiu_code": "6611", "description": "Administración de mercados financieros", "section_code": "SECCIÓN K", "section_name": "ACTIVIDADES FINANCIERAS Y DE SEGUROS"},
    {"ciiu_code": "6612", "description": "Corretaje de valores y de contratos de productos básicos", "section_code": "SECCIÓN K", "section_name": "ACTIVIDADES FINANCIERAS Y DE SEGUROS"},
    {"ciiu_code": "6613", "description": "Otras actividades relacionadas con el mercado de valores", "section_code": "SECCIÓN K", "section_name": "ACTIVIDADES FINANCIERAS Y DE SEGUROS"},
    {"ciiu_code": "6614", "description": "Actividades de las sociedades de intermediación cambiaria y de servicios financieros especiales", "section_code": "SECCIÓN K", "section_name": "ACTIVIDADES FINANCIERAS Y DE SEGUROS"},
    {"ciiu_code": "6615", "description": "Actividades de los profesionales de compra y venta de divisas", "section_code": "SECCIÓN K", "section_name": "ACTIVIDADES FINANCIERAS Y DE SEGUROS"},
    {"ciiu_code": "6619", "description": "Otras actividades auxiliares de las actividades de servicios financieros n.c.p.", "section_code": "SECCIÓN K", "section_name": "ACTIVIDADES FINANCIERAS Y DE SEGUROS"},
    {"ciiu_code": "6621", "description": "Actividades de agentes y corredores de seguros", "section_code": "SECCIÓN K", "section_name": "ACTIVIDADES FINANCIERAS Y DE SEGUROS"},
    {"ciiu_code": "6629", "description": "Evaluación de riesgos y daños, y otras actividades de servicios auxiliares", "section_code": "SECCIÓN K", "section_name": "ACTIVIDADES FINANCIERAS Y DE SEGUROS"},
    {"ciiu_code": "6630", "description": "Actividades de administración de fondos", "section_code": "SECCIÓN K", "section_name": "ACTIVIDADES FINANCIERAS Y DE SEGUROS"},
    {"ciiu_code": "6810", "description": "Actividades inmobiliarias realizadas con bienes propios o arrendados", "section_code": "SECCIÓN L", "section_name": "ACTIVIDADES INMOBILIARIAS"},
    {"ciiu_code": "6820", "description": "Actividades inmobiliarias realizadas a cambio de una retribución o por contrata", "section_code": "SECCIÓN L", "section_name": "ACTIVIDADES INMOBILIARIAS"},
    {"ciiu_code": "6910", "description": "Actividades jurídicas", "section_code": "SECCIÓN M", "section_name": "ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS"},
    {"ciiu_code": "6920", "description": "Actividades de contabilidad, teneduría de libros, auditoría financiera y asesoría tributaria", "section_code": "SECCIÓN M", "section_name": "ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS"},
    {"ciiu_code": "7010", "description": "Actividades de administración empresarial", "section_code": "SECCIÓN M", "section_name": "ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS"},
    {"ciiu_code": "7020", "description": "Actividades de consultoría de gestión", "section_code": "SECCIÓN M", "section_name": "ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS"},
    {"ciiu_code": "7111", "description": "Actividades de arquitectura", "section_code": "SECCIÓN M", "section_name": "ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS"},
    {"ciiu_code": "7112", "description": "Actividades de ingeniería y otras actividades conexas de consultoría técnica", "section_code": "SECCIÓN M", "section_name": "ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS"},
    {"ciiu_code": "7120", "description": "Ensayos y análisis técnicos", "section_code": "SECCIÓN M", "section_name": "ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS"},
    {"ciiu_code": "7210", "description": "Investigaciones y desarrollo experimental en el campo de las ciencias naturales y la ingeniería", "section_code": "SECCIÓN M", "section_name": "ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS"},
    {"ciiu_code": "7220", "description": "Investigaciones y desarrollo experimental en el campo de las ciencias sociales y las humanidades", "section_code": "SECCIÓN M", "section_name": "ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS"},
    {"ciiu_code": "7310", "description": "Publicidad", "section_code": "SECCIÓN M", "section_name": "ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS"},
    {"ciiu_code": "7320", "description": "Estudios de mercado y realización de encuestas de opinión pública", "section_code": "SECCIÓN M", "section_name": "ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS"},
    {"ciiu_code": "7410", "description": "Actividades especializadas de diseño", "section_code": "SECCIÓN M", "section_name": "ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS"},
    {"ciiu_code": "7420", "description": "Actividades de fotografía", "section_code": "SECCIÓN M", "section_name": "ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS"},
    {"ciiu_code": "7490", "description": "Otras actividades profesionales, científicas y técnicas n.c.p.", "section_code": "SECCIÓN M", "section_name": "ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS"},
    {"ciiu_code": "7500", "description": "Actividades veterinarias", "section_code": "SECCIÓN M", "section_name": "ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS"},
    {"ciiu_code": "7710", "description": "Alquiler y arrendamiento de vehículos automotores", "section_code": "SECCIÓN N", "section_name": "ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO"},
    {"ciiu_code": "7721", "description": "Alquiler y arrendamiento de equipo recreativo y deportivo", "section_code": "SECCIÓN N", "section_name": "ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO"},
    {"ciiu_code": "7722", "description": "Alquiler de videos y discos", "section_code": "SECCIÓN N", "section_name": "ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO"},
    {"ciiu_code": "7729", "description": "Alquiler y arrendamiento de otros efectos personales y enseres domésticos n.c.p.", "section_code": "SECCIÓN N", "section_name": "ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO"},
    {"ciiu_code": "7730", "description": "Alquiler y arrendamiento de otros tipos de maquinaria, equipo y bienes tangibles n.c.p.", "section_code": "SECCIÓN N", "section_name": "ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO"},
    {"ciiu_code": "7740", "description": "Arrendamiento de propiedad intelectual y productos similares, excepto obras protegidas por derechos de autor", "section_code": "SECCIÓN N", "section_name": "ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO"},
    {"ciiu_code": "7810", "description": "Actividades de agencias de gestión y colocación de empleo", "section_code": "SECCIÓN N", "section_name": "ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO"},
    {"ciiu_code": "7820", "description": "Actividades de empresas de servicios temporales", "section_code": "SECCIÓN N", "section_name": "ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO"},
    {"ciiu_code": "7830", "description": "Otras actividades de provisión de talento humano", "section_code": "SECCIÓN N", "section_name": "ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO"},
    {"ciiu_code": "7911", "description": "Actividades de las agencias de viaje", "section_code": "SECCIÓN N", "section_name": "ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO"},
    {"ciiu_code": "7912", "description": "Actividades de operadores turísticos", "section_code": "SECCIÓN N", "section_name": "ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO"},
    {"ciiu_code": "7990", "description": "Otros servicios de reserva y actividades relacionadas", "section_code": "SECCIÓN N", "section_name": "ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO"},
    {"ciiu_code": "8010", "description": "Actividades de seguridad privada", "section_code": "SECCIÓN N", "section_name": "ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO"},
    {"ciiu_code": "8020", "description": "Actividades de servicios de sistemas de seguridad", "section_code": "SECCIÓN N", "section_name": "ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO"},
    {"ciiu_code": "8030", "description": "Actividades de detectives e investigadores privados", "section_code": "SECCIÓN N", "section_name": "ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO"},
    {"ciiu_code": "8110", "description": "Actividades combinadas de apoyo a instalaciones", "section_code": "SECCIÓN N", "section_name": "ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO"},
    {"ciiu_code": "8121", "description": "Limpieza general interior de edificios", "section_code": "SECCIÓN N", "section_name": "ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO"},
    {"ciiu_code": "8129", "description": "Otras actividades de limpieza de edificios e instalaciones industriales", "section_code": "SECCIÓN N", "section_name": "ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO"},
    {"ciiu_code": "8130", "description": "Actividades de paisajismo y servicios de mantenimiento conexos", "section_code": "SECCIÓN N", "section_name": "ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO"},
    {"ciiu_code": "8211", "description": "Actividades combinadas de servicios administrativos de oficina", "section_code": "SECCIÓN N", "section_name": "ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO"},
    {"ciiu_code": "8219", "description": "Fotocopiado, preparación de documentos y otras actividades especializadas de apoyo a oficina", "section_code": "SECCIÓN N", "section_name": "ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO"},
    {"ciiu_code": "8220", "description": "Actividades de centros de llamadas (Call center)", "section_code": "SECCIÓN N", "section_name": "ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO"},
    {"ciiu_code": "8230", "description": "Organización de convenciones y eventos comerciales", "section_code": "SECCIÓN N", "section_name": "ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO"},
    {"ciiu_code": "8291", "description": "Actividades de agencias de cobranza y oficinas de calificación crediticia", "section_code": "SECCIÓN N", "section_name": "ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO"},
    {"ciiu_code": "8292", "description": "Actividades de envase y empaque", "section_code": "SECCIÓN N", "section_name": "ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO"},
    {"ciiu_code": "8299", "description": "Otras actividades de servicio de apoyo a las empresas n.c.p.", "section_code": "SECCIÓN N", "section_name": "ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO"},
    {"ciiu_code": "8411", "description": "Actividades legislativas de la administración pública", "section_code": "SECCIÓN O", "section_name": "ADMINISTRACIÓN PÚBLICA Y DEFENSA; PLANES DE SEGURIDAD SOCIAL DE AFILIACIÓN OBLIGATORIA"},
    {"ciiu_code": "8412", "description": "Actividades ejecutivas de la administración pública", "section_code": "SECCIÓN O", "section_name": "ADMINISTRACIÓN PÚBLICA Y DEFENSA; PLANES DE SEGURIDAD SOCIAL DE AFILIACIÓN OBLIGATORIA"},
    {"ciiu_code": "8413", "description": "Regulación de las actividades de organismos que prestan servicios de salud, educativos, culturales y otros servicios sociales, excepto servicios de seguridad social", "section_code": "SECCIÓN O", "section_name": "ADMINISTRACIÓN PÚBLICA Y DEFENSA; PLANES DE SEGURIDAD SOCIAL DE AFILIACIÓN OBLIGATORIA"},
    {"ciiu_code": "8414", "description": "Actividades reguladoras y facilitadoras de la actividad económica", "section_code": "SECCIÓN O", "section_name": "ADMINISTRACIÓN PÚBLICA Y DEFENSA; PLANES DE SEGURIDAD SOCIAL DE AFILIACIÓN OBLIGATORIA"},
    {"ciiu_code": "8415", "description": "Actividades de los otros órganos de control y otras instituciones", "section_code": "SECCIÓN O", "section_name": "ADMINISTRACIÓN PÚBLICA Y DEFENSA; PLANES DE SEGURIDAD SOCIAL DE AFILIACIÓN OBLIGATORIA"},
    {"ciiu_code": "8421", "description": "Relaciones exteriores", "section_code": "SECCIÓN O", "section_name": "ADMINISTRACIÓN PÚBLICA Y DEFENSA; PLANES DE SEGURIDAD SOCIAL DE AFILIACIÓN OBLIGATORIA"},
    {"ciiu_code": "8422", "description": "Actividades de defensa", "section_code": "SECCIÓN O", "section_name": "ADMINISTRACIÓN PÚBLICA Y DEFENSA; PLANES DE SEGURIDAD SOCIAL DE AFILIACIÓN OBLIGATORIA"},
    {"ciiu_code": "8423", "description": "Orden público y actividades de seguridad", "section_code": "SECCIÓN O", "section_name": "ADMINISTRACIÓN PÚBLICA Y DEFENSA; PLANES DE SEGURIDAD SOCIAL DE AFILIACIÓN OBLIGATORIA"},
    {"ciiu_code": "8424", "description": "Administración de justicia", "section_code": "SECCIÓN O", "section_name": "ADMINISTRACIÓN PÚBLICA Y DEFENSA; PLANES DE SEGURIDAD SOCIAL DE AFILIACIÓN OBLIGATORIA"},
    {"ciiu_code": "8430", "description": "Actividades de planes de seguridad social de afiliación obligatoria", "section_code": "SECCIÓN O", "section_name": "ADMINISTRACIÓN PÚBLICA Y DEFENSA; PLANES DE SEGURIDAD SOCIAL DE AFILIACIÓN OBLIGATORIA"},
    {"ciiu_code": "8511", "description": "Educación de la primera infancia", "section_code": "SECCIÓN P", "section_name": "EDUCACIÓN"},
    {"ciiu_code": "8512", "description": "Educación preescolar", "section_code": "SECCIÓN P", "section_name": "EDUCACIÓN"},
    {"ciiu_code": "8513", "description": "Educación básica primaria", "section_code": "SECCIÓN P", "section_name": "EDUCACIÓN"},
    {"ciiu_code": "8521", "description": "Educación básica secundaria", "section_code": "SECCIÓN P", "section_name": "EDUCACIÓN"},
    {"ciiu_code": "8522", "description": "Educación media académica", "section_code": "SECCIÓN P", "section_name": "EDUCACIÓN"},
    {"ciiu_code": "8523", "description": "Educación media técnica", "section_code": "SECCIÓN P", "section_name": "EDUCACIÓN"},
    {"ciiu_code": "8530", "description": "Establecimientos que combinan diferentes niveles de educación", "section_code": "SECCIÓN P", "section_name": "EDUCACIÓN"},
    {"ciiu_code": "8541", "description": "Educación técnica profesional", "section_code": "SECCIÓN P", "section_name": "EDUCACIÓN"},
    {"ciiu_code": "8542", "description": "Educación tecnológica", "section_code": "SECCIÓN P", "section_name": "EDUCACIÓN"},
    {"ciiu_code": "8543", "description": "Educación de instituciones universitarias o de escuelas tecnológicas", "section_code": "SECCIÓN P", "section_name": "EDUCACIÓN"},
    {"ciiu_code": "8544", "description": "Educación de universidades", "section_code": "SECCIÓN P", "section_name": "EDUCACIÓN"},
    {"ciiu_code": "8551", "description": "Formación para el trabajo", "section_code": "SECCIÓN P", "section_name": "EDUCACIÓN"},
    {"ciiu_code": "8552", "description": "Enseñanza deportiva y recreativa", "section_code": "SECCIÓN P", "section_name": "EDUCACIÓN"},
    {"ciiu_code": "8553", "description": "Enseñanza cultural", "section_code": "SECCIÓN P", "section_name": "EDUCACIÓN"},
    {"ciiu_code": "8559", "description": "Otros tipos de educación n.c.p.", "section_code": "SECCIÓN P", "section_name": "EDUCACIÓN"},
    {"ciiu_code": "8560", "description": "Actividades de apoyo a la educación", "section_code": "SECCIÓN P", "section_name": "EDUCACIÓN"},
    {"ciiu_code": "8610", "description": "Actividades de hospitales y clínicas, con internación", "section_code": "SECCIÓN Q", "section_name": "ACTIVIDADES DE ATENCIÓN DE LA SALUD HUMANA Y DE ASISTENCIA SOCIAL"},
    {"ciiu_code": "8621", "description": "Actividades de la práctica médica, sin internación", "section_code": "SECCIÓN Q", "section_name": "ACTIVIDADES DE ATENCIÓN DE LA SALUD HUMANA Y DE ASISTENCIA SOCIAL"},
    {"ciiu_code": "8622", "description": "Actividades de la práctica odontológica", "section_code": "SECCIÓN Q", "section_name": "ACTIVIDADES DE ATENCIÓN DE LA SALUD HUMANA Y DE ASISTENCIA SOCIAL"},
    {"ciiu_code": "8691", "description": "Actividades de apoyo diagnóstico", "section_code": "SECCIÓN Q", "section_name": "ACTIVIDADES DE ATENCIÓN DE LA SALUD HUMANA Y DE ASISTENCIA SOCIAL"},
    {"ciiu_code": "8692", "description": "Actividades de apoyo terapéutico", "section_code": "SECCIÓN Q", "section_name": "ACTIVIDADES DE ATENCIÓN DE LA SALUD HUMANA Y DE ASISTENCIA SOCIAL"},
    {"ciiu_code": "8699", "description": "Otras actividades de atención de la salud humana", "section_code": "SECCIÓN Q", "section_name": "ACTIVIDADES DE ATENCIÓN DE LA SALUD HUMANA Y DE ASISTENCIA SOCIAL"},
    {"ciiu_code": "8710", "description": "Actividades de atención residencial medicalizada de tipo general", "section_code": "SECCIÓN Q", "section_name": "ACTIVIDADES DE ATENCIÓN DE LA SALUD HUMANA Y DE ASISTENCIA SOCIAL"},
    {"ciiu_code": "8720", "description": "Actividades de atención residencial, para el cuidado de pacientes con retardo mental, enfermedad mental y consumo de sustancias psicoactivas", "section_code": "SECCIÓN Q", "section_name": "ACTIVIDADES DE ATENCIÓN DE LA SALUD HUMANA Y DE ASISTENCIA SOCIAL"},
    {"ciiu_code": "8730", "description": "Actividades de atención en instituciones para el cuidado de personas mayores y/o discapacitadas", "section_code": "SECCIÓN Q", "section_name": "ACTIVIDADES DE ATENCIÓN DE LA SALUD HUMANA Y DE ASISTENCIA SOCIAL"},
    {"ciiu_code": "8790", "description": "Otras actividades de atención en instituciones con alojamiento", "section_code": "SECCIÓN Q", "section_name": "ACTIVIDADES DE ATENCIÓN DE LA SALUD HUMANA Y DE ASISTENCIA SOCIAL"},
    {"ciiu_code": "8810", "description": "Actividades de asistencia social sin alojamiento para personas mayores y discapacitadas", "section_code": "SECCIÓN Q", "section_name": "ACTIVIDADES DE ATENCIÓN DE LA SALUD HUMANA Y DE ASISTENCIA SOCIAL"},
    {"ciiu_code": "8891", "description": "Actividades de guarderías para niños y niñas", "section_code": "SECCIÓN Q", "section_name": "ACTIVIDADES DE ATENCIÓN DE LA SALUD HUMANA Y DE ASISTENCIA SOCIAL"},
    {"ciiu_code": "8899", "description": "Otras actividades de asistencia social n.c.p.", "section_code": "SECCIÓN Q", "section_name": "ACTIVIDADES DE ATENCIÓN DE LA SALUD HUMANA Y DE ASISTENCIA SOCIAL"},
    {"ciiu_code": "9001", "description": "Creación literaria", "section_code": "SECCIÓN R", "section_name": "ACTIVIDADES ARTÍSTICAS, DE ENTRETENIMIENTO Y RECREACIÓN"},
    {"ciiu_code": "9002", "description": "Creación musical", "section_code": "SECCIÓN R", "section_name": "ACTIVIDADES ARTÍSTICAS, DE ENTRETENIMIENTO Y RECREACIÓN"},
    {"ciiu_code": "9003", "description": "Creación teatral", "section_code": "SECCIÓN R", "section_name": "ACTIVIDADES ARTÍSTICAS, DE ENTRETENIMIENTO Y RECREACIÓN"},
    {"ciiu_code": "9004", "description": "Creación audiovisual", "section_code": "SECCIÓN R", "section_name": "ACTIVIDADES ARTÍSTICAS, DE ENTRETENIMIENTO Y RECREACIÓN"},
    {"ciiu_code": "9005", "description": "Artes plásticas y visuales", "section_code": "SECCIÓN R", "section_name": "ACTIVIDADES ARTÍSTICAS, DE ENTRETENIMIENTO Y RECREACIÓN"},
    {"ciiu_code": "9006", "description": "Actividades teatrales", "section_code": "SECCIÓN R", "section_name": "ACTIVIDADES ARTÍSTICAS, DE ENTRETENIMIENTO Y RECREACIÓN"},
    {"ciiu_code": "9007", "description": "Actividades de espectáculos musicales en vivo", "section_code": "SECCIÓN R", "section_name": "ACTIVIDADES ARTÍSTICAS, DE ENTRETENIMIENTO Y RECREACIÓN"},
    {"ciiu_code": "9008", "description": "Otras actividades de espectáculos en vivo n.c.p.", "section_code": "SECCIÓN R", "section_name": "ACTIVIDADES ARTÍSTICAS, DE ENTRETENIMIENTO Y RECREACIÓN"},
    {"ciiu_code": "9101", "description": "Actividades de bibliotecas y archivos", "section_code": "SECCIÓN R", "section_name": "ACTIVIDADES ARTÍSTICAS, DE ENTRETENIMIENTO Y RECREACIÓN"},
    {"ciiu_code": "9102", "description": "Actividades y funcionamiento de museos, conservación de edificios y sitios históricos", "section_code": "SECCIÓN R", "section_name": "ACTIVIDADES ARTÍSTICAS, DE ENTRETENIMIENTO Y RECREACIÓN"},
    {"ciiu_code": "9103", "description": "Actividades de jardines botánicos, zoológicos y reservas naturales", "section_code": "SECCIÓN R", "section_name": "ACTIVIDADES ARTÍSTICAS, DE ENTRETENIMIENTO Y RECREACIÓN"},
    {"ciiu_code": "9200", "description": "Actividades de juegos de azar y apuestas", "section_code": "SECCIÓN R", "section_name": "ACTIVIDADES ARTÍSTICAS, DE ENTRETENIMIENTO Y RECREACIÓN"},
    {"ciiu_code": "9311", "description": "Gestión de instalaciones deportivas", "section_code": "SECCIÓN R", "section_name": "ACTIVIDADES ARTÍSTICAS, DE ENTRETENIMIENTO Y RECREACIÓN"},
    {"ciiu_code": "9312", "description": "Actividades de clubes deportivos", "section_code": "SECCIÓN R", "section_name": "ACTIVIDADES ARTÍSTICAS, DE ENTRETENIMIENTO Y RECREACIÓN"},
    {"ciiu_code": "9319", "description": "Otras actividades deportivas", "section_code": "SECCIÓN R", "section_name": "ACTIVIDADES ARTÍSTICAS, DE ENTRETENIMIENTO Y RECREACIÓN"},
    {"ciiu_code": "9321", "description": "Actividades de parques de atracciones y parques temáticos", "section_code": "SECCIÓN R", "section_name": "ACTIVIDADES ARTÍSTICAS, DE ENTRETENIMIENTO Y RECREACIÓN"},
    {"ciiu_code": "9329", "description": "Otras actividades recreativas y de esparcimiento n.c.p.", "section_code": "SECCIÓN R", "section_name": "ACTIVIDADES ARTÍSTICAS, DE ENTRETENIMIENTO Y RECREACIÓN"},
    {"ciiu_code": "9411", "description": "Actividades de asociaciones empresariales y de empleadores", "section_code": "SECCIÓN S", "section_name": "OTRAS ACTIVIDADES DE SERVICIOS"},
    {"ciiu_code": "9412", "description": "Actividades de asociaciones profesionales", "section_code": "SECCIÓN S", "section_name": "OTRAS ACTIVIDADES DE SERVICIOS"},
    {"ciiu_code": "9420", "description": "Actividades de sindicatos de empleados", "section_code": "SECCIÓN S", "section_name": "OTRAS ACTIVIDADES DE SERVICIOS"},
    {"ciiu_code": "9491", "description": "Actividades de asociaciones religiosas", "section_code": "SECCIÓN S", "section_name": "OTRAS ACTIVIDADES DE SERVICIOS"},
    {"ciiu_code": "9492", "description": "Actividades de asociaciones políticas", "section_code": "SECCIÓN S", "section_name": "OTRAS ACTIVIDADES DE SERVICIOS"},
    {"ciiu_code": "9499", "description": "Actividades de otras asociaciones n.c.p.", "section_code": "SECCIÓN S", "section_name": "OTRAS ACTIVIDADES DE SERVICIOS"},
    {"ciiu_code": "9511", "description": "Mantenimiento y reparación de computadores y de equipo periférico", "section_code": "SECCIÓN S", "section_name": "OTRAS ACTIVIDADES DE SERVICIOS"},
    {"ciiu_code": "9512", "description": "Mantenimiento y reparación de equipos de comunicación", "section_code": "SECCIÓN S", "section_name": "OTRAS ACTIVIDADES DE SERVICIOS"},
    {"ciiu_code": "9521", "description": "Mantenimiento y reparación de aparatos electrónicos de consumo", "section_code": "SECCIÓN S", "section_name": "OTRAS ACTIVIDADES DE SERVICIOS"},
    {"ciiu_code": "9522", "description": "Mantenimiento y reparación de aparatos y equipos domésticos y de jardinería", "section_code": "SECCIÓN S", "section_name": "OTRAS ACTIVIDADES DE SERVICIOS"},
    {"ciiu_code": "9523", "description": "Reparación de calzado y artículos de cuero", "section_code": "SECCIÓN S", "section_name": "OTRAS ACTIVIDADES DE SERVICIOS"},
    {"ciiu_code": "9524", "description": "Reparación de muebles y accesorios para el hogar", "section_code": "SECCIÓN S", "section_name": "OTRAS ACTIVIDADES DE SERVICIOS"},
    {"ciiu_code": "9529", "description": "Mantenimiento y reparación de otros efectos personales y enseres domésticos", "section_code": "SECCIÓN S", "section_name": "OTRAS ACTIVIDADES DE SERVICIOS"},
    {"ciiu_code": "9601", "description": "Lavado y limpieza, incluso la limpieza en seco, de productos textiles y de piel", "section_code": "SECCIÓN S", "section_name": "OTRAS ACTIVIDADES DE SERVICIOS"},
    {"ciiu_code": "9602", "description": "Peluquería y otros tratamientos de belleza", "section_code": "SECCIÓN S", "section_name": "OTRAS ACTIVIDADES DE SERVICIOS"},
    {"ciiu_code": "9603", "description": "Pompas fúnebres y actividades relacionadas", "section_code": "SECCIÓN S", "section_name": "OTRAS ACTIVIDADES DE SERVICIOS"},
    {"ciiu_code": "9609", "description": "Otras actividades de servicios personales n.c.p.", "section_code": "SECCIÓN S", "section_name": "OTRAS ACTIVIDADES DE SERVICIOS"},
    {"ciiu_code": "9700", "description": "Actividades de los hogares individuales como empleadores de personal doméstico", "section_code": "SECCIÓN T", "section_name": "ACTIVIDADES DE LOS HOGARES INDIVIDUALES EN CALIDAD DE EMPLEADORES; ACTIVIDADES NO DIFERENCIADAS DE LOS HOGARES INDIVIDUALES COMO PRODUCTORES DE BIENES Y SERVICIOS PARA USO PROPIO"},
    {"ciiu_code": "9810", "description": "Actividades no diferenciadas de los hogares individuales como productores de bienes para uso propio", "section_code": "SECCIÓN T", "section_name": "ACTIVIDADES DE LOS HOGARES INDIVIDUALES EN CALIDAD DE EMPLEADORES; ACTIVIDADES NO DIFERENCIADAS DE LOS HOGARES INDIVIDUALES COMO PRODUCTORES DE BIENES Y SERVICIOS PARA USO PROPIO"},
    {"ciiu_code": "9820", "description": "Actividades no diferenciadas de los hogares individuales como productores de servicios para uso propio", "section_code": "SECCIÓN T", "section_name": "ACTIVIDADES DE LOS HOGARES INDIVIDUALES EN CALIDAD DE EMPLEADORES; ACTIVIDADES NO DIFERENCIADAS DE LOS HOGARES INDIVIDUALES COMO PRODUCTORES DE BIENES Y SERVICIOS PARA USO PROPIO"},
    {"ciiu_code": "9900", "description": "Actividades de organizaciones y entidades extraterritoriales", "section_code": "SECCIÓN U", "section_name": "ACTIVIDADES DE ORGANIZACIONES Y ENTIDADES EXTRATERRITORIALES"},
    {"ciiu_code": "0010", "description": "Asalariados", "section_code": "SECCIÓN Dian", "section_name": "OTRAS CLASIFICACIONES (No hace parte de la CIIU Rev. 4 A.C 2020, es una sección establecida por la Dian)"},
    {"ciiu_code": "0020", "description": "Pensionados", "section_code": "SECCIÓN Dian", "section_name": "OTRAS CLASIFICACIONES (No hace parte de la CIIU Rev. 4 A.C 2020, es una sección establecida por la Dian)"},
    {"ciiu_code": "0081", "description": "Personas naturales y sucesiones ilíquidas sin actividad económica", "section_code": "SECCIÓN Dian", "section_name": "OTRAS CLASIFICACIONES (No hace parte de la CIIU Rev. 4 A.C 2020, es una sección establecida por la Dian)"},
    {"ciiu_code": "0082", "description": "Personas naturales subsidiadas por terceros", "section_code": "SECCIÓN Dian", "section_name": "OTRAS CLASIFICACIONES (No hace parte de la CIIU Rev. 4 A.C 2020, es una sección establecida por la Dian)"},
    {"ciiu_code": "0090", "description": "Rentistas de capital, solo para personas naturales y sucesiones ilíquidas", "section_code": "SECCIÓN Dian", "section_name": "OTRAS CLASIFICACIONES (No hace parte de la CIIU Rev. 4 A.C 2020, es una sección establecida por la Dian)"},
]